name: test
on:
  schedule:
      - cron:  '0 12 * * *'
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1'
      - uses: actions/checkout@v1
      - run: go test ./...
